apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-nmms
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ghpe-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-nmms@sha256:15fa6538c9b92138dfdbb3eaa2ea16794a9194fc5ea2a9eeba334f1570f7f985
        name: my-python
        resources: {}
status: {}
